version: 0.2

phases:
  install:
    commands:
      - pip --version && pip install aws-shell && aws --version
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - sleep 60
      - echo Build finished on `date`
  post_build:
    commands:
      - echo Build completed on `date`
